import {
  siCss,
  siExpress,
  siFigma,
  siFlutter,
  siGit,
  siGithub,
  siHtml5,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siOpenjdk,
  siPostgresql,
  siPostman,
  siReact,
  siSpringboot,
  siTailwindcss,
  siTypescript,
  type SimpleIcon,
} from "simple-icons";

export const skillIconMap: Record<string, SimpleIcon> = {
  git: siGit,
  github: siGithub,
  postman: siPostman,
  figma: siFigma,
  html: siHtml5,
  css: siCss,
  java: siOpenjdk,
  react: siReact,
  "next.js": siNextdotjs,
  nextjs: siNextdotjs,
  typescript: siTypescript,
  "tailwind css": siTailwindcss,
  tailwind: siTailwindcss,
  "node.js": siNodedotjs,
  nodejs: siNodedotjs,
  "express.js": siExpress,
  express: siExpress,
  "spring boot": siSpringboot,
  springboot: siSpringboot,
  postgresql: siPostgresql,
  mysql: siMysql,
  mongodb: siMongodb,
  flutter: siFlutter,
};

export const knownSkillNames = [
  "Git",
  "GitHub",
  "Postman",
  "Figma",
  "HTML",
  "CSS",
  "Java",
  "React",
  "Next.js",
  "TypeScript",
  "Tailwind CSS",
  "Node.js",
  "Express.js",
  "Spring Boot",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Flutter",
];
